package shop.customer;
//combines with CustomerService to give Model
import org.springframework.data.jpa.repository.JpaRepository;

public interface CustomerRepository extends JpaRepository<Customer, Integer>{
// tells spring that what u want to store in database and autogenerated integer
}